version: "3.9"

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # postgres configuration
    volumes:
      # persist data even if container shuts down
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: # named volumes can be managed easier using docker-compose
